Create comment-issue.yml
Meteor-Community-Packages/organization pull request #70
Opened 2022-11-21 05:14 UTC by jankapunkt

## What

Proposal for automated comments of newly created issues

## Why

Let contributors know they can also open a PR for trivial issues and that sponsoring is important :-D

## Checklist

- [ ] Agreed upon solution from issue #
- [ ] Stakeholders have approved the changes

2022-12-05 09:54 UTC, jankapunkt commented
@StorytellerCZ if you think this is okay I would add this to all our repositories

2022-12-06 09:33 UTC, StorytellerCZ requested changes

2022-12-06 09:33 UTC, StorytellerCZ commented on .github/workflows/comment-issue.yml
> +            THerefore, we can't guarantee you issues to be solved within certain time.
Typo here.

2022-12-06 09:33 UTC, StorytellerCZ commented
Great idea! Definitely worthy addition.

2022-12-06 11:06 UTC, merged

2022-12-06 11:06 UTC, jankapunkt commented
Great, I will add this to the other repos now